export const ADD_TODO: string = 'ADD_TODO';
export const RESTRICTED_WORD_CLOSE_ALERT: string = 'RESTRICTED_WORD_CLOSE_ALERT';
export const RESTRICTED_WORD_OPEN_ALERT: string = 'RESTRICTED_WORD_OPEN_ALERT';
